# Generated by Django 5.2 on 2025-05-05 02:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_habit_user_habitcheckin_journalentry_moodentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='moodentry',
            name='mood',
            field=models.CharField(choices=[('ecstatic', '😄 Ecstatic'), ('happy', '🙂 Happy'), ('content', '😊 Content'), ('neutral', '😐 Neutral'), ('tired', '😴 Tired'), ('anxious', '😰 Anxious'), ('sad', '😢 Sad'), ('angry', '😠 Angry'), ('overwhelmed', '😩 Overwhelmed'), ('lonely', '🥺 Lonely'), ('grateful', '🙏 Grateful'), ('hopeful', '🌱 Hopeful'), ('nesting', '🪺 Nesting')], max_length=20),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_completed_onboarding', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
