# Generated by Django 5.2 on 2025-05-06 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_savedmeditation_savedrecipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moodentry',
            name='mood',
            field=models.IntegerField(),
        ),
    ]
