# Generated by Django 5.2 on 2025-05-07 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_moodentry_mood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moodentry',
            name='mood',
            field=models.CharField(choices=[('ecstatic', '😄 Ecstatic'), ('happy', '🙂 Happy'), ('content', '😊 Content'), ('neutral', '😐 Neutral'), ('tired', '😴 Tired'), ('anxious', '😰 Anxious'), ('sad', '😢 Sad'), ('angry', '😠 Angry'), ('overwhelmed', '😩 Overwhelmed'), ('lonely', '🥺 Lonely'), ('grateful', '🙏 Grateful'), ('hopeful', '🌱 Hopeful'), ('nesting', '🪺 Nesting')], max_length=20),
        ),
    ]
